enableImmutableInstalls: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "playwright"
  - "@openpgp/*"
  - "@protontech/*"

yarnPath: .yarn/releases/yarn-4.10.2.cjs
