version: 2
jobs:
   build:
     docker:
       - image: cimg/node:lts
     steps:
       - checkout
       - run: npm i
       - run: npm run lint
       - run: npm run test-type-definitions
       - run: npm test