version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10.9.0-stretch-browsers
     steps:
       - checkout
       - run: npm i
       - run: npm run lint
       - run: npm test
       - run: npm run test-type-definitions