version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.2.3
jobs:
    build:
        docker:
            - image: cimg/node:lts-browsers
        steps:
            - browser-tools/install-chrome
            - browser-tools/install-firefox
            - checkout
            - run: npm i
            - run: npm run lint
            - run: npm run test-type-definitions
            - run: npm test
