on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false # if tests for one version fail, continue with the rest
      matrix:
        # run on multiple platforms to test platform-specific code, if present
        # (e.g. webkit's WebCrypto API implementation is different in macOS vs Linux)
        runner: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.runner }}
    permissions: {}
    
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5

      - name: Install dependencies
        run: npm ci
      
      - if: ${{ matrix.runner  == 'ubuntu-latest' }}
        run: npm run lint
      - run: npm run test-type-definitions

      - name: Install Chrome
        run: npx playwright install --with-deps chromium

      - name: Install Firefox
        run: npx playwright install --with-deps firefox

      - name: Install Webkit
        run: npx playwright install --with-deps webkit

      - name: Run tests
        run: npm test
